name: LumsDekos
version: 1.19
description: A decorative plugin.
authors: [Gadse, Timiette]
depend: [Vault, DiscordSRV]


main: com.lum.LumsDekos
api-version: 1.14

commands:
  nick:
    description: 'Nickname command'
    aliases: [nickname]
  prefix:
    aliases: [pfx, cpfx]
    description: 'Prefix command'
    # All permissions should be the same for a plugin.
    # consider decos.<command> to make permissions consistent
    permission: cpfx.pfx
    permission-message: "§cYou're missing the following permission: §6<permission>"
  emote:
    aliases: [em, emoticon, emoji]
    description: 'Emoticons that go before and after prefix.'
    permission: cpfx.pfx
    permission-message: "§cYou're missing the following permission: §6<permission>"
  webhook:
    aliases: [whook, discordhook, discordwebhook, dhook, discordurl, webhookurl, setwebhook, sethook]
    description: 'Sets the webhook that this plugin uses to communicate with Discord server. Only runnable by console.'
  arrow:
    aliases: [arr, chatmarker, marker, msgprefix]
    description: 'Changes the color of the > before your chat message.'
    permission: cpfx.arrow
    permission-message: "§cYou're missing the following permission: §6<permission>"
  quote:
    description: 'Changes the text that is displayed when your name is hovered over.'
    permission: cpfx.custom
    permission-message: "§cYou're missing the following permission: §6<permission>"
  ignore:
    description: 'I wonder what this could be used for.'
  link:
    aliases: [web, website, url]
    description: 'For sending links.'
    permission: chat.links
    permission-message: "§cYou're missing the following permission: §6<permission>"
  color:
    aliases: [cc, chatcolor, chat]
    permission: chat.color
    description: 'For changing your chat color.'
    permission-message: "§cYou're missing the following permission: §6<permission>"
  me:
    aliases: [action, oorp]
    description: 'Do fancy stuff'
  specialchat:
    description: 'Have fun with it.'
  listenmode:
    aliases: [clisten, listen]
    description: 'Select the type of message you listen to through DiscordSRV. Values are bot, user, and all'
  channel:
    aliases: [channel, channelselect, chansel]
    description: 'Select the channel of our Discord you want to listen to. It takes the ID as the value.'
  talk:
    aliases: [charcmd, ccmd, characteraction]
    description: 'Get a specified character to send a message in Discord.'
  regchar:
    aliases: [registerchar, charregister, charreg]
    description: 'Register a character!'
  avatar:
    aliases: [charavatar, charav, avchar, avatarchar]
    description: 'Implement an avatar for a character.'
  delchar:
    aliases: [removechar, remchar, deletechar, killchar]
    description: 'Delete a character from your player file.'
  listchars:
    description: 'Command that, when used, iterates over the config file of the sender to show them what exactly is there.'
  tmode:
    aliases: [talkmode, talkingmode, seltalkmode]
    description: '/tmode (discord|minecraft|both)'